### ISSUE TITLE
trublesome queue

### ISSUE THREAD

**Issue by jaboy** [LogBlock/LogBlock#692] opened 2017-05-26 13:53 UTC
Hello, i get an error in my console every time someone places down a block in the world called "plots"
The error does not show up for other worlds.

The error goes like this
```YAML
[15:30:13] [Craft Scheduler Thread - 9797/ERROR]: [Consumer] Troublesome query: HikariPreparedStatementProxy@889006790 wrapping com.mysql.jdbc.JDBC42PreparedStatement@1e254eae: INSERT INTO `lb-Plots` (date, playerid, replaced, type, data, x, y, z) VALUES(FROM_UNIXTIME(1495805413), 10364, 2, 0, 0, -902, 66, -66)
[15:30:13] [Craft Scheduler Thread - 9797/ERROR]: [Consumer] SQL exception on insertion: 
com.mysql.jdbc.exceptions.jdbc4.MySQLDataException: '2.54478238E9' in column '1' is outside valid range for the datatype INTEGER.
	at sun.reflect.GeneratedConstructorAccessor114.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at com.mysql.jdbc.ResultSetImpl.throwRangeException(ResultSetImpl.java:7074) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at com.mysql.jdbc.ResultSetImpl.parseIntAsDouble(ResultSetImpl.java:6352) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2510) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at de.diddiz.LogBlock.Consumer$BlockRow.executeStatements(Consumer.java:866) ~[LogBlock.jar:?]
	at de.diddiz.LogBlock.Consumer.run(Consumer.java:633) [LogBlock.jar:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
The log is still saved, even though the error is showed
If i attempt to connect to the mysql server, and enter the queue myself, mysql reports no errors.

My plugin version is (according to the loading message in console)
git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
LogBlock v1.11-SNAPSHOT (build #275)
LogBlockQuestioner v0.02

The table scheme for the plots world currently looks like this
```mysql
CREATE TABLE `lb-Plots` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `date` datetime NOT NULL,
  `playerid` int(10) unsigned NOT NULL,
  `replaced` tinyint(3) unsigned NOT NULL,
  `type` tinyint(3) unsigned NOT NULL,
  `data` tinyint(3) unsigned NOT NULL,
  `x` mediumint(9) NOT NULL,
  `y` smallint(5) unsigned NOT NULL,
  `z` mediumint(9) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `coords` (`x`,`z`,`y`),
  KEY `date` (`date`),
  KEY `playerid` (`playerid`)
) ENGINE=InnoDB AUTO_INCREMENT=2544974672 DEFAULT CHARSET=latin1;
```

**Comment by Brokkonaut** [comment] 2018-08-01 20:27
Duplicate of #654

**Closed by Brokkonaut** 2018-08-01 20:27 UTC
