### ISSUE TITLE
REF unable to clear table entries #593

### ISSUE THREAD

**Issue by frizzbee30** [LogBlock/LogBlock#594] opened 2015-03-07 09:31 UTC
Hi, Logblock is still unable to clear the table, I have tried multiple mixes of Survival map, "survival_map" survival "survival" survival_map and each time it stumbles with the space.
 Is there any way to adopt using an alias, as our world uses 'survival' as an alias, but logblock is unable to look this up?  This has been an issue with another plugin, and the author was able to adopt using the alias.
 The actual table entry is lb-Survival_Map so I'm surprised it doesn't recognise Survival_Map, but I'm presuming it is looking at the world name as opposed to the table name in the command. Is there any way as an alternative to directly address the tables via the clear command?  Thanks

**Comment by frymaster** [comment] 2015-03-07 15:10
Hi, please post a fresh pastebin of the error and of that section of your config.yml

**Comment by frizzbee30** [comment] 2015-03-07 22:18
Hi, paste's from test server  (test database hosted alongside live) with quotes in  :) Thanks for looking at this.

Config  http://pastebin.com/3p49KhEi      (world config filename is Survival Map.yml


Log  http://pastebin.com/SWGKb6B6


Log after console command lb clearlog "Survival Map" 
 [22:12:04] [Server thread/INFO]: [0;31;1mNot a valid argument: '"survival'[m

**Comment by frizzbee30** [comment] 2015-03-07 22:18
all the other worlds clear great

**Comment by frymaster** [comment] 2015-03-10 15:41
aha, I think it's the nuances of the YML parser that is the problem here

try:

``- "world \"Survival Map\" before 14 days all"``

**Comment by frizzbee30** [comment] 2015-03-11 20:20
Thanks, I'll try that. it may be  a path to use with other YAML configs  :)

**Comment by frizzbee30** [comment] 2015-03-11 20:47
Hi, strangely it converts the config back to http://pastebin.com/3p49KhEi and thus produces the same error. i've tried a few times as at first I thought I had somehow forgot to save the YML

**Comment by frymaster** [comment] 2015-03-11 20:53
fantastic.  What's happening is, LogBlock prepares a default config, reads the config file (if any) and merges it over the top of the default config, and then saves it back out.  This is so if there's any new config options, they show up in your config.

The problem appears to be **the YAML system is outputting text in a way the parser can't read in**.  That's all kinds of special :/

I'm going to look into this a bit more

**Comment by frymaster** [comment] 2015-03-11 21:08
oh hang on

>Log after console command lb clearlog "Survival Map" 

Yeah, that **isn't** valid

clearlog works like other commands.  The thing in the config file is just a scheduler for those commands.  So the config means every 8 hours it runs ``lb clearlog world "Survival Map" before 14 days all``

You typing ``/lb clearlog "Survival Map"`` doesn't mean "invoke the thing from the config", it means "run clearlog with the parameters Survival Map" which does indeed make no sense

If you want to run it manually you have to type all the parameters ie  ``/lb clearlog world "Survival Map" before 14 days all``.  Basically it's exactly the same as lookup except it nukes the results instead of displaying them to you

**Comment by frizzbee30** [comment] 2015-03-11 22:10
Thanks, i can probably schedule the full command via console. is the space issue in the YML config for the scheduled clear something that it is possible to resolve (possibly via alias?) or is it just going to be a quirk of the parser and our 'unusual' world naming convention?  (not set by me, i don;t like spaces either). Cheers

**Comment by frizzbee30** [comment] 2015-03-11 22:15
Hi, tried /lb clearlog world "Survival Map" before 14 days all as a command and got, not a valid argument map returned  (still hates the space I'm guessing?)

**Comment by frymaster** [comment] 2015-03-11 22:34
yeah, it's definitely not the config but the actual command parsing.  This is really confusing me since I read through the code last night and I swear it should work.  I can reproduce the error on my test setup, so I'll have another look for the root cause.  I've never had occasion to look into that part of the code before so I'm not overly familiar with it

**Comment by frizzbee30** [comment] 2015-03-12 20:11
Thanks, I know it's a real pain in the "you know what", and you could easily say..don't leave dumb spaces in your world names! Very much appreciated anyway!  :D

**Comment by ammaraskar** [comment] 2015-03-20 14:10
Fixed with https://github.com/LogBlock/LogBlock/commit/1a0a742daa67a5f702cb6edfc813811ad81a63ad

**Closed by ammaraskar** 2015-03-20 14:10 UTC
Labels: Bug, Commands
